name: .python_packages
channels:
  - defaults
dependencies:
  - flask=2.1.3
  - numpy=1.23.4
  - pip=22.2.2
  - python=3.9.13
  - r-base=3.6.1
  - r-randomforest=4.6_14
  - requests=2.28.1
  - pip:
    - azure-functions==1.12.0
    - rpy2==3.4.5
